// Plugins used in the project
plugins {
    id 'java-gradle-plugin'
	id 'maven-publish'
}

// Change java compatibility level to 23
sourceCompatibility = targetCompatibility = 23

def snapshot = project.release ? "" : "-SNAPSHOT"
version = project.version+snapshot
// Name, version and group for the project
version = "1.3"
group = "com.minecrafttas"
archivesBaseName = "discombobulator"

// Configure the gradle plugin
gradlePlugin {
    plugins {
        discombobulator {
            id = 'discombobulator'
            implementationClass = 'com.minecrafttas.discombobulator.Discombobulator'
        }
    }
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation(platform('org.junit:junit-bom:5.11.3'))
	testImplementation('org.junit.jupiter:junit-jupiter')
	implementation 'commons-io:commons-io:2.17.0'
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}

java {
    withSourcesJar()
    withJavadocJar()
}

javadoc {
	options.locale = "en_US"
	options.addBooleanOption('Xdoclint:none', true)
}

publishToMavenLocal {
	version = version + "-SNAPSHOT"
}

publishing {
	repositories {
		maven {
			name = "minecrafttasSnapshots"
			url = "https://maven.minecrafttas.com/snapshots"
			credentials(PasswordCredentials)
			authentication {
				basic(BasicAuthentication)
			}
		}
		maven {
			name = "minecrafttasMain"
			url = "https://maven.minecrafttas.com/main"
			credentials(PasswordCredentials)
			authentication {
				basic(BasicAuthentication)
			}
		}
	}
}