name: Test Discombobulator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: 7.6
    - name: Test
      run: gradle test
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3.7.4
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
