name: test

on:
  push:
#    branches:
#      - develop
  pull_request:
    branches:
      - main
      - develop
      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: 7.6
    - name: Test
      run: gradle test
    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: always() # always run even if the previous step fails
      with:
        name: junit-test-results
        path: '**/build/test-results/test/TEST-*.xml'
        retention-days: 1

---
name: report
on:
  workflow_run:
    workflows: [test]
    types: [completed]
    
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2.26.0
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.7.4
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/build/test-results/test/TEST-*.xml'